# Generated by Django 5.0.1 on 2026-02-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="batterymodel",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
