# Generated by Django 5.0.1 on 2026-02-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warranty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyClaimAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="warranties/claims/")),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="warranty.warrantyclaim",
                    ),
                ),
            ],
            options={
                "db_table": "warranty_claim_attachments",
                "ordering": ["-created_at"],
            },
        ),
    ]
