<?php

return [
    'provider_enabled' => env('REGISTRATION_PROVIDER_ENABLED', false),
    'provider_driver' => env('REGISTRATION_PROVIDER_DRIVER', 'null'),
    'provider_name' => env('REGISTRATION_PROVIDER_NAME', 'none'),
    'cache_ttl_minutes' => (int) env('REGISTRATION_LOOKUP_CACHE_TTL', 1440),
    'http' => [
        'url' => env('REGISTRATION_PROVIDER_HTTP_URL', ''),
        'method' => env('REGISTRATION_PROVIDER_HTTP_METHOD', 'GET'),
        'profile' => env('REGISTRATION_PROVIDER_HTTP_PROFILE', 'generic'),
        'token' => env('REGISTRATION_PROVIDER_HTTP_TOKEN', ''),
        'auth_mode' => env('REGISTRATION_PROVIDER_HTTP_AUTH_MODE', 'header'),
        'token_header' => env('REGISTRATION_PROVIDER_HTTP_TOKEN_HEADER', 'Authorization'),
        'token_prefix' => env('REGISTRATION_PROVIDER_HTTP_TOKEN_PREFIX', 'Bearer'),
        'token_query_param' => env('REGISTRATION_PROVIDER_HTTP_TOKEN_QUERY_PARAM', 'api_key'),
        'payload_mode' => env('REGISTRATION_PROVIDER_HTTP_PAYLOAD_MODE', 'auto'),
        'vehicle_path' => env('REGISTRATION_PROVIDER_HTTP_VEHICLE_PATH', 'vehicle'),
        'rego_param' => env('REGISTRATION_PROVIDER_HTTP_REGO_PARAM', 'registration_number'),
        'state_param' => env('REGISTRATION_PROVIDER_HTTP_STATE_PARAM', 'state_code'),
        'market_param' => env('REGISTRATION_PROVIDER_HTTP_MARKET_PARAM', 'market'),
        'make_keys' => ['make', 'manufacturer', 'vehicle_make'],
        'model_keys' => ['model', 'vehicle_model'],
        'year_keys' => ['year', 'model_year', 'build_year'],
        'variant_keys' => ['variant', 'series', 'trim'],
        'profiles' => [
            'generic' => [],
            'au_nz_adapter' => [
                'rego_param' => 'plate',
                'state_param' => 'jurisdiction',
                'market_param' => 'country',
                'vehicle_path' => 'data.vehicle',
                'make_keys' => ['manufacturer_name', 'make'],
                'model_keys' => ['model_name', 'model'],
                'year_keys' => ['year_of_manufacture', 'year'],
                'variant_keys' => ['series', 'variant', 'trim_name'],
            ],
        ],
        'market_profiles' => [
            'AU' => env('REGISTRATION_PROVIDER_HTTP_PROFILE_AU', 'au_nz_adapter'),
            'NZ' => env('REGISTRATION_PROVIDER_HTTP_PROFILE_NZ', 'au_nz_adapter'),
        ],
        'timeout_seconds' => (int) env('REGISTRATION_PROVIDER_HTTP_TIMEOUT', 10),
    ],
];
